export const beginner = [
  { en: "Hello", tr: "Merhaba" },
  { en: "Mom", tr: "Anne" },
  { en: "accountant", tr: "muhasebeci" },
  { en: "afraid", tr: "korkmak" },
  { en: "age", tr: "yaş" },
  { en: "alone", tr: "yalnız" },
  { en: "airplane", tr: "uçak" },
  { en: "angry", tr: "kızgın" },
  { en: "animal", tr: "hayvan" },
  { en: "answer", tr: "cevap" },
  { en: "architect", tr: "mimar" },
  { en: "arrive", tr: "varmak" },
  { en: "aunt", tr: "hala, teyze" },
  { en: "bag", tr: "çanta" },
  { en: "ball", tr: "top" },
  { en: "bath", tr: "banyo" },
  { en: "beautiful", tr: "güzel" },
];
