export const beginner = [
  { en: "Hello", tr: "Merhaba" },
  { en: "Mom", tr: "Anne" },
  { en: "accountant", tr: "muhasebeci" },
  { en: "afraid", tr: "korkmak" },
  { en: "age", tr: "yaş" },
  { en: "alone", tr: "yalnız" },
  { en: "airplane", tr: "uçak" },
  { en: "angry", tr: "kızgın" },
  { en: "animal", tr: "hayvan" },
  { en: "answer", tr: "cevap" },
  { en: "architect", tr: "mimar" },
  { en: "arrive", tr: "varmak" },
  { en: "aunt", tr: "hala, teyze" },
  { en: "bag", tr: "çanta" },
  { en: "ball", tr: "top" },
  { en: "bath", tr: "banyo" },
  { en: "beautiful", tr: "güzel" },
  { en: "bill", tr: "fatura" },
  { en: "body", tr: "vücut" },
  { en: "boil", tr: "kaynamak, kaynatmak" },
  { en: "bookstore", tr: "kitapevi" },
  { en: "boring", tr: "sıkıcı" },
  { en: "borrow", tr: "ödünç almak, borç almak" },
  { en: "boss", tr: "patron" },
  { en: "bottle", tr: "şişe" },
  { en: "box", tr: "kutu" },
  { en: "brave", tr: "cesur" },
  { en: "bread", tr: "ekmek" },
  { en: "break", tr: "kırmak" },
  { en: "bridge", tr: "köprü" },
  { en: "brush", tr: "fırça, fırçalamak" },
  { en: "build", tr: "inşa etmek" },
  { en: "butter", tr: "tere yağ" },
  { en: "calculator", tr: "hesap makinesi" },
  { en: "calendar", tr: "takvim" },
  { en: "call", tr: "aramak, çağırmak" },
  { en: "capital", tr: "sermaye, başkent" },
  { en: "carpenter", tr: "marangoz" },
  { en: "carpet", tr: "halı" },
  { en: "carry", tr: "taşımak" },
  { en: "cartoon", tr: "çizgi film" },
  { en: "chair", tr: "sandalye" },
  { en: "cheap", tr: "ucuz" },
  { en: "cheese", tr: "peynir" },
  { en: "cherry", tr: "kiraz" },
  { en: "chicken", tr: "piliç" },
  { en: "church", tr: "kilise" },
  { en: "clean", tr: "temizlemek, temiz" },
  { en: "clear", tr: "açık, belli, temiz" },
  { en: "clever", tr: "zeki" },
  { en: "clock", tr: "saat" },
  { en: "cloud", tr: "bulut" },
  { en: "coat", tr: "ceket" },
  { en: "cold", tr: "soğuk" },
  { en: "company", tr: "şirket" },
  { en: "continue", tr: "devam etmek" },
  { en: "correct", tr: "doğru, düzeltmek" },
  { en: "country", tr: "ülke" },
  { en: "cow", tr: "inek" },
  { en: "cry", tr: "ağlamak" },
  { en: "daily", tr: "günlük" },
  { en: "dark", tr: "koyu" },
  { en: "dentist", tr: "dişçi" },
  { en: "difficult", tr: "zor" },
  { en: "dirty", tr: "pis" },
  { en: "divorced", tr: "boşanmış" },
  { en: "draw", tr: "çizmek" },
  { en: "early", tr: "erken" },
  { en: "earn", tr: "para kazanmak" },
  { en: "elephant", tr: "fil" },
  { en: "emergency", tr: "acil, tehlike" },
  { en: "empty", tr: "boş" },
  { en: "engaged", tr: "nişanlı, bağlı" },
  { en: "engineer", tr: "mühendis" },
  { en: "enough", tr: "yeterli" },
  { en: "eraser", tr: "silgi" },
  { en: "error", tr: "hata" },
  { en: "fall", tr: "düşmek, inmek" },
  { en: "far", tr: "uzak" },
  { en: "farm", tr: "tarla" },
  { en: "fat", tr: "şişman" },
  { en: "finger", tr: "parmak" },
  { en: "fire", tr: "ateş" },
  { en: "flight", tr: "uçuş, uçakla seyahat" },
  { en: "floor", tr: "kat" },
  { en: "fork", tr: "çatal" },
  { en: "friendly", tr: "arkadaş canlısı, sıcak kanlı" },
  { en: "fruit", tr: "meyve" },
  { en: "funny", tr: "eğlenceli" },
  { en: "garden", tr: "bahçe" },
  { en: "glass", tr: "bardak" },
  { en: "grape", tr: "üzüm" },
  { en: "gun", tr: "silah, tabanca" },
  { en: "habit", tr: "alışkanlık" },
  { en: "half", tr: "yarım, yarı" },
  { en: "hand", tr: "el" },
  { en: "handsome", tr: "yakışıklı" },
  { en: "hate", tr: "nefret etmek" },
  { en: "health", tr: "iyileştirmek, sağlıklı" },
  { en: "hear", tr: "duymak" },
  { en: "heart", tr: "kalp" },
  { en: "high", tr: "yüksek" },
  { en: "history", tr: "tarih" },
  { en: "horror", tr: "korku, dehşet" },
  { en: "hungry", tr: "acıkmış olmak" },
  { en: "ill", tr: "hasta olmak" },
  { en: "interested", tr: "ilgili, alakalı" },
  { en: "job", tr: "iş" },
  { en: "journalist", tr: "gazeteci, gazeteci yazar" },
  { en: "kill", tr: "öldürmek" },
  { en: "large", tr: "büyük" },
  { en: "laugh", tr: "gülmek" },
  { en: "lawyer", tr: "avukat" },
  { en: "leave", tr: "ayrılmak" },
  { en: "left", tr: "sol" },
  { en: "lend", tr: "ödünç vermek" },
  { en: "letter", tr: "mektup, harf" },
  { en: "library", tr: "kütüphane" },
  { en: "light", tr: "ışık" },
  { en: "lunch", tr: "öğle yemeği" },
  { en: "manager", tr: "yönetici" },
  { en: "main", tr: "ana" },
  { en: "map", tr: "harita" },
  { en: "married", tr: "evli" },
  { en: "meal", tr: "yemek" },
  { en: "meet", tr: "tanışmak" },
  { en: "meeting", tr: "toplantı" },
  { en: "melon", tr: "kavun" },
  { en: "minute", tr: "dakika" },
  { en: "mirror", tr: "ayna" },
  { en: "miss", tr: "kaçırmak, özlemek" },
  { en: "mistake", tr: "hata" },
  { en: "month", tr: "ay" },
  { en: "need", tr: "ihtiyacı olmak" },
  { en: "neighbor", tr: "komşu" },
  { en: "news", tr: "haber" },
  { en: "nice", tr: "hoş" },
  { en: "nose", tr: "burun" },
  { en: "nurse", tr: "hemşire" },
  { en: "object", tr: "obje, nesne" },
  { en: "opposite", tr: "zıt, karşıt, ters" },
  { en: "oven", tr: "fırın" },
  { en: "page", tr: "sayfa" },
  { en: "paint", tr: "resim yapmak" },
  { en: "parent", tr: "ebeveyn" },
  { en: "pass", tr: "geçmek, geçiş" },
  { en: "pay", tr: "ödemek" },
  { en: "pepper", tr: "biber" },
  { en: "personal", tr: "kişisel" },
  { en: "pet", tr: "evcil hayvan" },
  { en: "place", tr: "yer" },
  { en: "plane", tr: "uçak" },
  { en: "pocket", tr: "cep" },
  { en: "polite", tr: "kibar" },
  { en: "pool", tr: "havuz" },
  { en: "poor", tr: "fakir" },
  { en: "possible", tr: "imkanlı" },
  { en: "push", tr: "itmek, basmak (tuşa)" },
  { en: "quick", tr: "çabuk" },
  { en: "quiet", tr: "sessiz" },
  { en: "railway", tr: "demiryolu" },
  { en: "ready", tr: "hazır" },
  { en: "refrigerator", tr: "buzdolabı" },
  { en: "remember", tr: "hatırlamak" },
  { en: "rent", tr: "kiralamak" },
  { en: "repair", tr: "tamir etmek" },
  { en: "repeat", tr: "tekrarlamak" },
  { en: "restroom", tr: "tuvalet" },
  { en: "return", tr: "geri dönmek" },
  { en: "rice", tr: "pirinç" },
  { en: "rich", tr: "zengin" },
  { en: "ride", tr: "sürmek" },
  { en: "right", tr: "sağ" },
  { en: "ring", tr: "çalmak" },
  { en: "rise", tr: "yükselmek, artış" },
  { en: "river", tr: "nehir" },
  { en: "road", tr: "yol" },
  { en: "roof", tr: "çatı" },
  { en: "room", tr: "oda" },
  { en: "rose", tr: "gül" },
  { en: "salt", tr: "tuz" },
  { en: "same", tr: "aynı" },
  { en: "security", tr: "güvenlik" },
  { en: "sell", tr: "satmak" },
  { en: "serious", tr: "ciddi" },
  { en: "shelf", tr: "raf" },
  { en: "ship", tr: "gemi" },
  { en: "shirt", tr: "gömlek" },
  { en: "shoe", tr: "ayakkabı" },
  { en: "show", tr: "göstermek" },
  { en: "sick", tr: "hasta" },
  { en: "sing", tr: "söylemek, şarkı söylemek" },
  { en: "single", tr: "tek, bekar" },
  { en: "skirt", tr: "etek" },
  { en: "sky", tr: "gökyüzü" },
  { en: "smile", tr: "gülümsemek" },
  { en: "snow", tr: "kar, kar yağışı" },
  { en: "socks", tr: "çorap" },
  { en: "son", tr: "evlat, oğul" },
  { en: "song", tr: "şarkı" },
  { en: "spend", tr: "harcamak" },
  { en: "spoon", tr: "kaşık" },
  { en: "stamp", tr: "pul" },
  { en: "stay", tr: "kalmak" },
  { en: "story", tr: "hikaye" },
  { en: "strawberry", tr: "çilek" },
  { en: "strong", tr: "güçlü" },
  { en: "successful", tr: "başarılı" },
  { en: "suit", tr: "uymak, takım elbise" },
  { en: "sweet", tr: "tatlı" },
  { en: "talk", tr: "konuşmak" },
  { en: "tall", tr: "uzun" },
  { en: "teach", tr: "öğretmek" },
  { en: "thick", tr: "kalın" },
  { en: "thief", tr: "hırsız" },
  { en: "thin", tr: "ince" },
  { en: "think", tr: "düşünmek" },
  { en: "thirsty", tr: "susamak" },
  { en: "ticket", tr: "bilet" },
  { en: "tidy", tr: "düzenli, derli toplu" },
  { en: "tired", tr: "yorulmuş olmak" },
  { en: "toothbrush", tr: "diş fırçası" },
  { en: "toothpaste", tr: "diş macunu" },
  { en: "towel", tr: "havlu" },
  { en: "tower", tr: "kule" },
  { en: "town", tr: "kent, şehir, kasaba" },
  { en: "toy", tr: "oyuncak" },
  { en: "trainers", tr: "spor ayakkabısı" },
  { en: "travel", tr: "seyehat, gezi" },
  { en: "tree", tr: "ağaç" },
  { en: "trousers", tr: "pantolon, kumaş pantolon" },
  { en: "turn", tr: "dönmek" },
  { en: "ugly", tr: "çirkin" },
  { en: "umbrella", tr: "şemsiye" },
  { en: "uncle", tr: "amca" },
  { en: "understand", tr: "anlamak" },
  { en: "underwear", tr: "iç çamaşır" },
  { en: "waiter", tr: "garson" },
  { en: "wall", tr: "duvar" },
  { en: "watermelon", tr: "karpuz" },
  { en: "way", tr: "taraf, tarz, yön" },
  { en: "weak", tr: "güçsüz" },
  { en: "wear", tr: "giyinmek" },
  { en: "week", tr: "hafta" },
  { en: "wind", tr: "rüzgar, sarmak, dolamak" },
  { en: "winter", tr: "kış" },
  { en: "wonderful", tr: "mükemmel, harkulade" },
  { en: "word", tr: "kelime" },
  { en: "wrong", tr: "yanlış" },
  { en: "zoo", tr: "hayvanat bahçesi" },
  { en: "abroad", tr: "yurt dışına" },
  { en: "accept", tr: "kabullenmek, kabul etmek" },
  { en: "accident", tr: "kaza yapmak" },
  { en: "adventure", tr: "macera" },
  { en: "agree", tr: "katılmak, aynı fikirde olmak" },
  { en: "anniversary", tr: "yıllık" },
  { en: "ant", tr: "karınca" },
];
