export const intermediate = [
  { en: "admit", tr: "kabul etmek, itiraf etmek" },
  { en: "advertise", tr: "reklam etmek" },
  { en: "advocate", tr: "avukat" },
  { en: "affair", tr: "dalga, vaka, mesele" },
  { en: "agreement", tr: "anlaşma" },
  { en: "agriculture", tr: "tarım" },
  { en: "aim", tr: "amaç" },
  { en: "aisle", tr: "koridor" },
  { en: "allowance", tr: "müsaade, ödenek, izin" },
  { en: "ambassador", tr: "büyük elçi" },
  { en: "amusement", tr: "şaşırtıcı" },
  { en: "ancient", tr: "eskiden kalma, tarihi, ata" },
  { en: "anticipate", tr: "ummak, beklemek" },
  { en: "apparent", tr: "görünür, aşikar, ortada" },
  { en: "appearance", tr: "görünüş, dış görünüş" },
  { en: "appreciate", tr: "takdir etmek, beğenmek" },
  { en: "appropriate", tr: "münasip, uygun" },
  { en: "approve", tr: "kabul etmek, uygun bulmak" },
  { en: "argument", tr: "argüman" },
  { en: "arrest", tr: "tutuklamak" },
  { en: "audience", tr: "dinleyici" },
  { en: "avoid", tr: "kaçınmak, önlemek" },
  { en: "baggage claim", tr: "bagaj teslim" },
  { en: "balance sheet", tr: "bilanço, denge tablosu" },
  { en: "bank account", tr: "banka hesabı" },
  { en: "bankrupt", tr: "iflas etmek" },
  { en: "bargain", tr: "pazarlık" },
  { en: "beg", tr: "yalvarmak" },
  { en: "beggar", tr: "dilenci" },
  { en: "blame", tr: "ayıplamak, suçlamak" },
  { en: "board of directors", tr: "yönetim kurulu" },
  { en: "breath", tr: "nefes, soluk" },
  { en: "bribe", tr: "rüşvet" },
  { en: "budget", tr: "bütçe" },
  { en: "candidate", tr: "aday" },
  { en: "cash flow", tr: "nakit akışı" },
  { en: "cemetery", tr: "mezarlık" },
  { en: "chamber of commerce", tr: "ticaret odası" },
  { en: "charming", tr: "çekici, cazibeli, alımlı" },
  { en: "chief executive", tr: "başkan" },
  { en: "circumstance", tr: "durum, hal" },
  { en: "claim", tr: "talep etmek, iddia etmek" },
  { en: "clerk", tr: "satıcı" },
  { en: "client", tr: "müşteri" },
  { en: "coal", tr: "kömür" },
  { en: "comment", tr: "yorumlamak, yorum" },
  { en: "commerce", tr: "ticaret" },
  { en: "commercial", tr: "ticari" },
  { en: "community", tr: "cemaat, topluluk, camia" },
  { en: "competition", tr: "yarışma, rekabet" },
  { en: "complaint", tr: "şikayet" },
  { en: "concentrate", tr: "konsantre olmak" },
  { en: "condition", tr: "hal,durum, şart" },
  { en: "confess", tr: "itiraf etmek" },
  { en: "congratulate", tr: "tebrik etmek" },
  { en: "congress", tr: "kongre" },
  { en: "consider", tr: "dikkate almak, hesaba katmak" },
  { en: "construction", tr: "inşaat, yapı" },
  { en: "consult", tr: "danışmak" },
  { en: "contest", tr: "yarışma" },
  { en: "contribute", tr: "katkı yapmak, katkıda bulunmak" },
  { en: "convert", tr: "dönüştürmek" },
  { en: "court", tr: "mahkeme" },
  { en: "crossword", tr: "çapraz bulmaca" },
  { en: "cruel", tr: "zalim" },
  { en: "customs", tr: "gümrük" },
  { en: "dashboard", tr: "gösterge çizelgesi, çamurluk" },
  { en: "deadline", tr: "son teslim tarihi" },
  { en: "deceive", tr: "aldatmak, kandırmak" },
  { en: "declare", tr: "ilan etmeki, beyan etmek" },
  { en: "define", tr: "tanımlamak" },
  { en: "deflation", tr: "sönme, deflasyon" },
  { en: "depend", tr: "bağlı olmak" },
  { en: "desire", tr: "istek duymak, istemek, arzulamak" },
  { en: "devaluation", tr: "devalüasyon, değer düşümü" },
  { en: "diagnose", tr: "tedavi" },
  { en: "disappear", tr: "gözden kaybolmak, yok olmak, ortadan kaybolmak" },
  { en: "disappoint", tr: "hayal kırıklığına uğramak" },
  { en: "distance", tr: "uzaklık" },
  { en: "distribution", tr: "dağıtma, dağıtım, dağılım" },
  { en: "dreadful", tr: "rezil" },
  { en: "eager", tr: "istekli" },
  { en: "election", tr: "seçim" },
  { en: "embassy", tr: "büyükelçilik" },
  { en: "encourage", tr: "cesaretlendirmek" },
  { en: "enemy", tr: "düşman" },
  { en: "enterprise", tr: "girişim, teşebbüs" },
  { en: "entrepreneur", tr: "girişimci, müteşebbis" },
  { en: "envy", tr: "imrenmek, kıskançlık" },
  { en: "essay", tr: "kalkışmak, tecrübe etmek" },
  { en: "establish", tr: "kurmak" },
  { en: "estimate", tr: "tahmin etmek, kestirmek" },
  { en: "evaluate", tr: "değerlendirmek" },
  { en: "evidence", tr: "kanıt, delil" },
  { en: "exaggerate", tr: "abartmak" },
  { en: "examine", tr: "incelemek, muayene etmek" },
  { en: "exchange rate", tr: "döviz kuru" },
  { en: "exhibition", tr: "sergi" },
  { en: "experiment", tr: "deney" },
  { en: "fame", tr: "ün, söhret, nam" },
  { en: "fence", tr: "çit" },
  { en: "fix", tr: "düzeltmek, onarmak, tamir etmek" },
  { en: "fluent", tr: "akıcı" },
  { en: "foolish", tr: "aptalca, ahmak, akılsız" },
  { en: "forecast", tr: "tahmin etmek, tahmin" },
  { en: "fragile", tr: "kırılgan, hassas, narin" },
  { en: "frame", tr: "çerçeve" },
  { en: "franchise", tr: "hak, bağışıklık, üyelik" },
  { en: "frequent", tr: "sık" },
  { en: "fund raising", tr: "para toplama" },
  { en: "gamble", tr: "kumar" },
  { en: "gear transmission", tr: "aktarma dişlileri" },
  { en: "globalization", tr: "globelleşme" },
  { en: "government", tr: "hükümet" },
  { en: "grateful", tr: "minnettar" },
  { en: "growth rate", tr: "büyüme oranı" },
  { en: "hair dryer", tr: "fön, saç kurutma makinesi" },
  { en: "harvest", tr: "hasat" },
  { en: "hesitate", tr: "tereddüt etmek" },
  { en: "hire", tr: "kiralamak" },
  { en: "hitch hike", tr: "otostop çekmek, otostop yapmak" },
  { en: "homesick", tr: "ev hasreti çeken, gurbet çeken" },
  { en: "identification", tr: "kimlik saptama" },
  { en: "in advance", tr: "önceden, peşin" },
  { en: "include", tr: "katmak, içermek, kapsamak" },
  { en: "income", tr: "kazanç, gelir" },
  { en: "increase", tr: "artmak, çoğalmak, arttırmak" },
  { en: "independent", tr: "bağımsız" },
  { en: "inflation", tr: "abartı, enflasyon, şime" },
  { en: "innocent", tr: "masum" },
  { en: "inspection", tr: "muayene, denetleme" },
  { en: "inspector", tr: "müfettiş" },
  { en: "insurance", tr: "sigorta" },
  { en: "interest rate", tr: "faiz oranı" },
  { en: "invoice", tr: "fatura" },
  { en: "judge", tr: "yargılamak, yargıç, hakim" },
  { en: "justice", tr: "adalet" },
  { en: "kidnapping", tr: "çocuk kaçırmak, kaçırmak" },
  { en: "knowledge", tr: "bilgi" },
  { en: "labor force", tr: "iş gücü" },
  { en: "landlord", tr: "ev sahibi" },
  { en: "licence plate", tr: "ehliyet" },
  { en: "life vest", tr: "emniyet kemeri" },
  { en: "loan", tr: "borç, kredi, ödünç para" },
  { en: "loan agreement", tr: "kredi sözleşmesi" },
  { en: "magnification", tr: "büyütme" },
  { en: "maintain", tr: "sürdürme, bakım yapmak" },
  { en: "market share", tr: "Pazar paylaşımı" },
  { en: "marketing research", tr: "Pazar araştırması" },
  { en: "marvellous", tr: "fevkalade, harkulade" },
  { en: "massive", tr: "cüsseli, iri, çok büyük" },
  { en: "member of parliament", tr: "milletvekili" },
  { en: "mention", tr: "bahsetmek, söz etmek" },
  { en: "merchandise", tr: "ticaret yapmak, alıp satmak" },
  { en: "nation", tr: "ulus" },
  { en: "net capital", tr: "net sermaye" },
  { en: "objective", tr: "objektif" },
  { en: "observe", tr: "gözlemlemek" },
  { en: "obvious", tr: "besbelli" },
  { en: "opportunity", tr: "imkan, olanak" },
  { en: "participate", tr: "katılımcı" },
  { en: "patience", tr: "sabır" },
  { en: "percentage", tr: "yüzde" },
  { en: "persuade", tr: "ikna etmek" },
  { en: "pollution", tr: "kirlilik" },
  { en: "postpone", tr: "ötelemek, ertelemek" },
  { en: "president", tr: "baskan" },
  { en: "price control", tr: "fiyat denetimi" },
  { en: "prison", tr: "hapishane" },
  { en: "process", tr: "işlemek, işlem, süreç" },
  { en: "profit", tr: "yarar, çıkar, fayda" },
  { en: "prohibit", tr: "hasaklamak" },
  { en: "promotion", tr: "promosyon, tanıtım" },
  { en: "property", tr: "mal mülk, emlak" },
  { en: "proposal", tr: "teklif" },
  { en: "prove", tr: "kanıtlamak, ispat etmek" },
  { en: "publicity", tr: "tanıtım, ilan etmek" },
  { en: "punctual", tr: "dakik" },
  { en: "punishment", tr: "ceza" },
  { en: "quantity", tr: "miktar" },
  { en: "quarrel", tr: "çekişmek, dalaşmak, tartışmak" },
  { en: "queue", tr: "sıraya girmek, sıra" },
  { en: "receipt", tr: "alındı, makbuz" },
  { en: "receive", tr: "teslim almak, almak" },
  { en: "recognize", tr: "tanımak" },
  { en: "recommend", tr: "önermek, tavsiye etmek" },
  { en: "reduce", tr: "eksiltmek, düşürmek" },
  { en: "rub", tr: "ovmak, sürtünmek, sürtmek" },
  { en: "schedule", tr: "program, plan" },
  { en: "regret", tr: "pişman olmak" },
  { en: "reject", tr: "reddetmek, geri çevirmek" },
  { en: "release", tr: "salıvermek, salmak, serbest bırakmak" },
  { en: "religion", tr: "din" },
  { en: "reluctant", tr: "gönülsüz, isteksiz" },
  { en: "rely", tr: "güvenmek" },
  { en: "represent", tr: "yansıtmak, temsil etmek" },
  { en: "request", tr: "talep etmek, rica etmek" },
  { en: "resolution", tr: "azim, kararlılık" },
  { en: "resource", tr: "kaynak" },
  { en: "respect", tr: "saygı, saygı göstemek" },
  { en: "respond", tr: "yanıtlamak, yanıt vermek" },
  { en: "revenue", tr: "gelir, hasılat" },
  { en: "revise", tr: "gözden geçirmek" },
  { en: "sand", tr: "kum" },
  { en: "science", tr: "bilim" },
  { en: "seek", tr: "aramak" },
  { en: "sense", tr: "hissetmek, algılamak" },
  { en: "shake", tr: "sallamak" },
  { en: "share", tr: "paylaşmak" },
  { en: "sink", tr: "batmak" },
  { en: "skyscraper", tr: "gökdelen" },
  { en: "steering wheel", tr: "direksiyon simidi" },
  { en: "strike", tr: "vurmak, çarpmak, darbe, grev" },
  { en: "substitute", tr: "yerine geçirmek, yedek" },
  { en: "supplier", tr: "tedarikçi" },
  { en: "suppose", tr: "zannetmek, varsaymak, sanmak" },
  { en: "swear", tr: "sövmek, küfür etmek" },
  { en: "take action", tr: "harekete geçmek" },
  { en: "take advantage", tr: "avantaj elde etmek" },
  { en: "task", tr: "görev" },
  { en: "tax", tr: "vergi" },
  { en: "throat", tr: "boğaz" },
  { en: "to book", tr: "rezervasyon yapmak" },
  { en: "torture", tr: "işkence" },
  { en: "trademark", tr: "ticari marka" },
  { en: "transmit", tr: "iletmek, ulaştırmak" },
  { en: "treat", tr: "tedavi etmek, davranmak, işlemek" },
  { en: "treatment", tr: "tedavi, muamele" },
  { en: "trick", tr: "kandırmak, dalavere, oyun etmek" },
  { en: "underline", tr: "vurgulamak" },
  { en: "unemployment", tr: "işsiz" },
  { en: "urgent", tr: "acil" },
  { en: "value added tax", tr: "kdv, katma değer vergisi" },
  { en: "violent", tr: "şiddetli" },
  { en: "volunteer", tr: "gönüllü olmak" },
  { en: "warehouse", tr: "depo" },
  { en: "wealthy", tr: "varlıklı, zengin" },
  { en: "weapon", tr: "silan" },
  { en: "whistle", tr: "fısıldamak" },
  { en: "wholesale", tr: "toptan satış" },
  { en: "witness", tr: "görgü şahiti, tanık, tanıklık etmek" },
  { en: "zip", tr: "fermuar" },
  { en: "gear", tr: "dişli, vites" },
  { en: "transmission", tr: "şanzıman, vites, iletim" },
];
