export const preIntermediate = [
  { en: "blanket", tr: "battaniye" },
  { en: "brain", tr: "beyin" },
  { en: "bring", tr: "getirmek" },
  { en: "business", tr: "iş" },
  { en: "busy", tr: "meşgul" },
  { en: "cable", tr: "kablo" },
  { en: "can", tr: "e bilmek" },
  { en: "cap", tr: "şapka , kep" },
  { en: "cash", tr: "nakit" },
  { en: "catch", tr: "yakalamak" },
  { en: "change", tr: "değişmek , değiştirmek" },
  { en: "changing room", tr: "giyinme kabini" },
  { en: "chess", tr: "satranç" },
  { en: "chewing gum", tr: "sakız" },
  { en: "chin", tr: "çene" },
  { en: "choose", tr: "seçmek" },
  { en: "climb", tr: "tırmanmak" },
  { en: "cloth", tr: "giyisi" },
  { en: "collect", tr: "toplamak" },
  { en: "complete", tr: "tamamlamak" },
  { en: "confused", tr: "aklı karışmak" },
  { en: "connect", tr: "bağlanmak" },
  { en: "contact", tr: "irtibat kurmak, irtibat" },
  { en: "cookie", tr: "kurabiye" },
  { en: "cool", tr: "serin, rahat" },
  { en: "cost", tr: "ücret, maliyet" },
  { en: "cotton", tr: "pamuk" },
  { en: "couch", tr: "koç, antrenör" },
  { en: "cough", tr: "öksürmek" },
  { en: "crazy", tr: "deli, manyak" },
  { en: "curious", tr: "meraklı" },
  { en: "customer", tr: "müşteri" },
  { en: "cut", tr: "kesmek" },
  { en: "cute", tr: "tatlı, şirin" },
  { en: "damage", tr: "zarar vermek" },
  { en: "dangerous", tr: "tehlikeli" },
  { en: "dead", tr: "ölü" },
  { en: "decide", tr: "karar vermek" },
  { en: "deep", tr: "dip, derin" },
  { en: "delete", tr: "silmek" },
  { en: "delicious", tr: "lezzetli" },
  { en: "describe", tr: "tanımlamak, tarif etmek, betimlemek" },
  { en: "diamond", tr: "elmas" },
  { en: "die", tr: "ölmek" },
  { en: "direction", tr: "yön, istikamet" },
  { en: "discover", tr: "keşfetmek" },
  { en: "discuss", tr: "görüşmek - tartışmak" },
  { en: "disturb", tr: "rahatsız etmek" },
  { en: "drawer", tr: "çekmece" },
  { en: "dream", tr: "rüya, hayal" },
  { en: "earring", tr: "küpe" },
  { en: "elbow", tr: "dirsek" },
  { en: "elevator", tr: "asansör" },
  { en: "enjoy", tr: "hoşlanmak" },
  { en: "entertainment", tr: "gösteri" },
  { en: "equal", tr: "eşit" },
  { en: "escape", tr: "kaçış, kaçmak" },
  { en: "excellent", tr: "mükemmel" },
  { en: "exhausted", tr: "yorgun olmak" },
  { en: "expensive", tr: "pahalı" },
  { en: "experience", tr: "tecrübe" },
  { en: "explain", tr: "açıklamak" },
  { en: "eyebrow", tr: "kaş" },
  { en: "eyelash", tr: "kirpik" },
  { en: "eyelid", tr: "göz kapağı" },
  { en: "face", tr: "yüz" },
  { en: "factory", tr: "fabrika" },
  { en: "fail", tr: "başarısız olmak" },
  { en: "famous", tr: "ünlü" },
  { en: "fan", tr: "fan" },
  { en: "feel", tr: "hissetmek" },
  { en: "female", tr: "bayan" },
  { en: "fight", tr: "dövüşmek, dövmek" },
  { en: "fill", tr: "doldurmak" },
  { en: "first aid", tr: "ilk yardım" },
  { en: "flag", tr: "bayrak" },
  { en: "flat", tr: "düz, daire (ev)" },
  { en: "flour", tr: "un" },
  { en: "fog", tr: "sis" },
  { en: "follow", tr: "takip etmek" },
  { en: "food", tr: "yiyecek" },
  { en: "foreign", tr: "yabancı" },
  { en: "formal", tr: "resmi" },
  { en: "fresh", tr: "ferah" },
  { en: "front", tr: "ön" },
  { en: "fuel", tr: "yakıt" },
  { en: "furniture", tr: "mobilya" },
  { en: "future", tr: "gelecek" },
  { en: "garlic", tr: "sarımsak" },
  { en: "gate", tr: "kapı" },
  { en: "generous", tr: "cömert" },
  { en: "gift", tr: "hediye" },
  { en: "glad", tr: "memnun olmak" },
  { en: "glove", tr: "eldiven" },
  { en: "graduate", tr: "mezun olmak" },
  { en: "grass", tr: "çim" },
  { en: "grocer", tr: "süpermarket" },
  { en: "grow", tr: "büyümek, yetiştirmek" },
  { en: "guide", tr: "rehber" },
  { en: "hard", tr: "zor" },
  { en: "harmful", tr: "zararlı" },
  { en: "huge", tr: "devasa" },
  { en: "idea", tr: "fikir, düşünce" },
  { en: "impossible", tr: "imkansız" },
  { en: "insect", tr: "böcek" },
  { en: "intelligent", tr: "zeki, akıllı" },
  { en: "introduce", tr: "tanıtmak, tanıştırmak" },
  { en: "invite", tr: "davet etmek" },
  { en: "island", tr: "ada" },
  { en: "jam", tr: "reçel" },
  { en: "jar", tr: "kavanoz" },
  { en: "join", tr: "katılmak" },
  { en: "joke", tr: "şaka" },
  { en: "journey", tr: "seyehat" },
  { en: "juice", tr: "meyve suyu" },
  { en: "jump", tr: "zıplamak" },
  { en: "key", tr: "anahtar" },
  { en: "kick", tr: "tekmelemek, tekme" },
  { en: "kind", tr: "çeşit, cins, nazik" },
  { en: "knee", tr: "diz, diz çökmek" },
  { en: "knife", tr: "bıçak" },
  { en: "lake", tr: "göl" },
  { en: "lamb", tr: "kuzu" },
  { en: "leather", tr: "deri" },
  { en: "leg", tr: "bacak" },
  { en: "lift", tr: "kaldırmak, asansör" },
  { en: "lip", tr: "dudak" },
  { en: "lock", tr: "kilitlemek, kilit" },
  { en: "lose", tr: "kaybetmek" },
  { en: "loud", tr: "yüksek sesle" },
  { en: "lovely", tr: "güzel" },
  { en: "luck", tr: "şans" },
  { en: "magic", tr: "büyü, sihir" },
  { en: "mall", tr: "alışveriş merkezi" },
  { en: "meat", tr: "et" },
  { en: "medicine", tr: "tıp, ilaç" },
  { en: "mend", tr: "onarmak" },
  { en: "mixed", tr: "karışık" },
  { en: "monkey", tr: "maymun" },
  { en: "moon", tr: "ay" },
  { en: "mountain", tr: "dağ" },
  { en: "mouth", tr: "ay (takvim)" },
  { en: "move", tr: "hareket etmek, taşınmak" },
  { en: "nail clippers", tr: "tırnak makası" },
  { en: "naughty", tr: "yaramaz" },
  { en: "nervous", tr: "sinirli, asabi" },
  { en: "noise", tr: "gürültü" },
  { en: "novel", tr: "roman" },
  { en: "ocean", tr: "okyanus" },
  { en: "officier", tr: "memur" },
  { en: "oil", tr: "yağ" },
  { en: "overweight", tr: "kilolu" },
  { en: "pick", tr: "seçmek" },
  { en: "plant", tr: "ekmek (v), dikmek, bitki" },
  { en: "plate", tr: "tabak" },
  { en: "poem", tr: "şiir" },
  { en: "point", tr: "nokta, uç, puan" },
  { en: "power", tr: "güç" },
  { en: "prepare", tr: "hazırlanmak" },
  { en: "pretty", tr: "sevimli" },
  { en: "price", tr: "fiyat, paha" },
  { en: "produce", tr: "üretmek" },
  { en: "queen", tr: "kraliçe" },
  { en: "reach", tr: "ulaşmak, erişmek" },
  { en: "reason", tr: "sebep" },
  { en: "record", tr: "kayıt" },
  { en: "refuse", tr: "reddetmek, geri çevirmek" },
  { en: "relation", tr: "ilişki" },
  { en: "relax", tr: "rahatlamak" },
  { en: "remote control", tr: "uzaktan kontrol" },
  { en: "reply", tr: "yanıtlamak, cevap" },
  { en: "report", tr: "bildirmek, rapor etmek" },
  { en: "retire", tr: "emekli olmak" },
  { en: "rock", tr: "kaya" },
  { en: "rope", tr: "ip" },
  { en: "rude", tr: "kaba" },
  { en: "rule", tr: "kural" },
  { en: "safe", tr: "güvenli, emniyetli" },
  { en: "salary", tr: "maaş" },
  { en: "save", tr: "kurtarmak" },
  { en: "scissors", tr: "makas" },
  { en: "seat", tr: "oturak, koltuk" },
  { en: "select", tr: "seçmek" },
  { en: "send", tr: "göndermek" },
  { en: "situation", tr: "durum, olay" },
  { en: "serve", tr: "hizmet etmek" },
  { en: "sharp", tr: "keskin" },
  { en: "shine", tr: "parlatmak, parlamak" },
  { en: "shoulder", tr: "omuz" },
  { en: "shout", tr: "bağırmak" },
  { en: "sign", tr: "imza, işaret" },
  { en: "silent", tr: "sessiz" },
  { en: "simple", tr: "basit" },
  { en: "ski", tr: "kayak" },
  { en: "snake", tr: "yılan" },
  { en: "soap", tr: "sabun" },
  { en: "society", tr: "halk, toplum" },
  { en: "soft", tr: "yumuşak" },
  { en: "spider", tr: "örümcek" },
  { en: "stand", tr: "durmak, ayakta durmak" },
  { en: "stone", tr: "taş" },
  { en: "storm", tr: "fırtına" },
  { en: "subway", tr: "metro" },
  { en: "sure", tr: "emin olmak" },
  { en: "surprised", tr: "şaşırmak" },
  { en: "tailor", tr: "terzi" },
  { en: "taste", tr: "tat, lezzet" },
  { en: "team", tr: "takım" },
  { en: "temperature", tr: "sıcaklık, derece" },
  { en: "tent", tr: "çadır" },
  { en: "terrible", tr: "korkunç, berbat" },
  { en: "throw", tr: "fırlatmak, atmak, atış" },
  { en: "tiger", tr: "kaplan" },
  { en: "tissue", tr: "doku" },
  { en: "tongue", tr: "dil" },
  { en: "touch", tr: "dokunmak" },
  { en: "transport", tr: "nakletmek" },
  { en: "trouble", tr: "sorun" },
  { en: "try", tr: "denemek" },
  { en: "usual", tr: "olağan" },
  { en: "vacation", tr: "izin, tatil" },
  { en: "vacuum cleaner", tr: "elektrikli süpürge" },
  { en: "valuable", tr: "değerli" },
  { en: "vegetable", tr: "bitki" },
  { en: "view", tr: "görüş, manzara" },
  { en: "voice", tr: "ses" },
  { en: "war", tr: "savaş" },
  { en: "warm", tr: "ılık, ısıtmak, ısınmak" },
  { en: "warning", tr: "ikaz, uyarı" },
  { en: "weather", tr: "hava" },
  { en: "wet", tr: "ıslak" },
  { en: "win", tr: "kazanmak" },
  { en: "wine", tr: "şarap" },
  { en: "worry", tr: "merak etmek, endişelenmek" },
  { en: "account", tr: "hesap" },
  { en: "accounts payable", tr: "alacaklı hesabı" },
  { en: "accounts receivable", tr: "alacak, senetsiz alacak" },
  { en: "accuse", tr: "suçlamak" },
  { en: "achievement", tr: "kazanım" },
  { en: "adjust", tr: "ayarlamak" },
];
