export const upperIntermediate = [
  { en: "abstract", tr: "soyut" },
  { en: "abuse", tr: "kötüye kullanmak, istismar etmek" },
  { en: "accordance", tr: "uyum, ahenk" },
  { en: "accurate", tr: "doğru" },
  { en: "acknowledge", tr: "kabul etmek" },
  { en: "acquire", tr: "elde etmek" },
  { en: "acquisition", tr: "edinim" },
  { en: "adequate", tr: "yeterli" },
  { en: "adjacent", tr: "bitişik" },
  { en: "allocate", tr: "pay etmek, bölüştürmek" },
  { en: "ally", tr: "müttefik" },
  { en: "antibody", tr: "antikor" },
  { en: "arch", tr: "kemer" },
  { en: "arrangement", tr: "düzenleme" },
  { en: "array", tr: "bir dizi-sıra" },
  { en: "artificial", tr: "yapay" },
  { en: "assess", tr: "değerlendirmek" },
  { en: "asset", tr: "varlık" },
  { en: "associate", tr: "ilişkilendirmek" },
  { en: "assume", tr: "varsaymak" },
  { en: "assure", tr: "garanti etmek" },
  { en: "auction", tr: "açık arttırma" },
  { en: "audit", tr: "denetlemek , hesap denetimi" },
  { en: "beam", tr: "işın" },
  { en: "binary", tr: "ikili" },
  { en: "boost", tr: "arttırmak" },
  { en: "breach", tr: "ihlal" },
  { en: "capture", tr: "ele geçirmek" },
  { en: "cease", tr: "durdurmak" },
  { en: "chorus", tr: "koro" },
  { en: "cluster", tr: "küme" },
  { en: "colleague", tr: "meslektaş" },
  { en: "commit", tr: "suç işlemek" },
  { en: "commodity", tr: "ticari mal" },
  { en: "compensation", tr: "tazminat" },
  { en: "comply", tr: "uymak (a)" },
  { en: "component", tr: "bileşen" },
  { en: "comprise", tr: "içermek, kapsamak" },
  { en: "conceive", tr: "tasarlamak, kurmak" },
  { en: "concerning", tr: "ilişkin" },
  { en: "conduct", tr: "yönetmek" },
  { en: "confine", tr: "sınırlamak" },
  { en: "confirm", tr: "onaylamak" },
  { en: "conflict", tr: "çatışma" },
  { en: "confront", tr: "yüzleştirmek" },
  { en: "conjunction", tr: "bağlaç" },
  { en: "consequence", tr: "sonuç" },
  { en: "consist of", tr: "-den oluşmak" },
  { en: "consonant", tr: "ünsüz" },
  { en: "constant", tr: "sürekli" },
  { en: "constitute", tr: "oluşturmak" },
  { en: "constraint", tr: "baski kisitlama zorlama" },
  { en: "context", tr: "bağlam" },
  { en: "contraction", tr: "kasılma" },
  { en: "contractor", tr: "müteahhit" },
  { en: "contrasting", tr: "zıt" },
  { en: "contribution", tr: "katkı" },
  { en: "conversation", tr: "konuşma" },
  { en: "convey", tr: "iletmek" },
  { en: "criticism", tr: "eleştiri" },
  { en: "crucial", tr: "çok önemli" },
  { en: "curb (v)", tr: "frenlemek" },
  { en: "curve", tr: "eğim, eğmek" },
  { en: "damp", tr: "nemli" },
  { en: "debtor", tr: "borçlu" },
  { en: "debut", tr: "sahneye ilk çıkış" },
  { en: "decade", tr: "on yıl" },
  { en: "decay", tr: "çürümek" },
  { en: "decline", tr: "azalmak" },
  { en: "dedicate", tr: "adamak" },
  { en: "deficit", tr: "eksiklik" },
  { en: "deliberate", tr: "kasti" },
  { en: "delicate", tr: "narin hassas" },
  { en: "density", tr: "yoğunluk" },
  { en: "depict", tr: "anlatmak" },
  { en: "depreciation", tr: "amortisman" },
  { en: "derivative", tr: "türev" },
  { en: "disapprove", tr: "onaylamamak" },
  { en: "discharge", tr: "deşarj" },
  { en: "discourse", tr: "konuşma" },
  { en: "dismiss", tr: "kovmak" },
  { en: "disposal", tr: "i̇mha etme" },
  { en: "dispute", tr: "tartışmak" },
  { en: "dissolve", tr: "eritmek" },
  { en: "distant", tr: "uzak" },
  { en: "distinct", tr: "farklı" },
  { en: "distinguish", tr: "ayırt etmek" },
  { en: "domestic", tr: "evcil" },
  { en: "dominate", tr: "hükmetmek" },
  { en: "due", tr: "vadesi dolmuş zamanı gelmiş" },
  { en: "efficient", tr: "verimli" },
  { en: "elaborate", tr: "ayrıntılı, detaylı" },
  { en: "elect", tr: "seçmek" },
  { en: "embrace", tr: "kucaklamak" },
  { en: "emerge", tr: "ortaya çıkmak" },
  { en: "encounter", tr: "karşılaşmak" },
  { en: "engage", tr: "1.nişanlamak 2.iş vermek" },
  { en: "enhance", tr: "geliştirmek" },
  { en: "enquiry", tr: "soruşturma" },
  { en: "ensure", tr: "garantiye almak" },
  { en: "equilibrium", tr: "denge, denklik, tarafsızlık" },
  { en: "equity", tr: "öz kaynak" },
  { en: "equivalent", tr: "eşdeğer" },
  { en: "essential", tr: "gerekli" },
  { en: "evolve", tr: "gelişmek" },
  { en: "exceed", tr: "aşmak" },
  { en: "exemption", tr: "muafiyet" },
  { en: "expand", tr: "genişletmek" },
  { en: "expense", tr: "masraf" },
  { en: "explode", tr: "patlamak" },
  { en: "exploit", tr: "sömürmek" },
  { en: "exploration", tr: "keşif" },
  { en: "expose", tr: "maruz bırakmak" },
  { en: "extend", tr: "uzatmak" },
  { en: "extract", tr: "elde etmek, çekip çıkarmak" },
  { en: "faintly", tr: "belli belirsiz" },
  { en: "faucet", tr: "musluk" },
  { en: "fiscal", tr: "mali" },
  { en: "fraction", tr: "kesir" },
  { en: "framework", tr: "yapı" },
  { en: "gain", tr: "kazanmak" },
  { en: "generate", tr: "üretmek" },
  { en: "genre (n)", tr: "tür" },
  { en: "genuine", tr: "hakiki, gerçek" },
  { en: "gesture", tr: "jest" },
  { en: "gradual", tr: "aşamalı" },
  { en: "grain", tr: "tahıl" },
  { en: "highlight", tr: "vurgulamak" },
  { en: "imperative", tr: "zorunlu" },
  { en: "implement", tr: "uygulamak" },
  { en: "implication", tr: "çıkarım, ima" },
  { en: "impose", tr: "zorla kabul ettirmek, koymak( vergi), yük olmak" },
  { en: "improvement", tr: "gelişim" },
  { en: "incentive", tr: "teşvik" },
  { en: "incidence", tr: "olay" },
  { en: "incur", tr: "uğramak" },
  { en: "indicate", tr: "belirtmek" },
  { en: "induce", tr: "ikna etmek, sebep olmak" },
  { en: "initial", tr: "ilk" },
  { en: "initiative", tr: "girişim" },
  { en: "interim", tr: "geçici" },
  { en: "interior", tr: "iç" },
  { en: "interpret", tr: "yorumlamak" },
  { en: "interrupt", tr: "sözünü kesmek" },
  { en: "interval", tr: "aralık" },
  { en: "intervention", tr: "müdahale" },
  { en: "irritate", tr: "kızdırmak" },
  { en: "justify", tr: "haklı çıkarmak" },
  { en: "keen", tr: "i̇stekli" },
  { en: "lean", tr: "dayanmak, yaslanmak" },
  { en: "leap", tr: "sıçramak" },
  { en: "linguistic", tr: "dilbilimsel" },
  { en: "loose", tr: "gevşek" },
  { en: "lump", tr: "yumru" },
  { en: "magnitude", tr: "büyüklük" },
  { en: "majority", tr: "çoğunluk" },
  { en: "manner", tr: "tavır" },
  { en: "marine", tr: "denize ait" },
  { en: "membrane", tr: "zar" },
  { en: "minority", tr: "azınlık" },
  { en: "monetary", tr: "parasal" },
  { en: "movement", tr: "hareket" },
  { en: "narrative", tr: "öykü" },
  { en: "narrator", tr: "hikayeci" },
  { en: "noticeable", tr: "dikkate değer" },
  { en: "obscure", tr: "belirsiz" },
  { en: "obtain", tr: "elde etmek" },
  { en: "occasion", tr: "fırsat" },
  { en: "occupy", tr: "işgal etmek" },
  { en: "occur", tr: "meydana gelmek" },
  { en: "opponent", tr: "rakip" },
  { en: "oppose", tr: "karşı çıkmak" },
  { en: "ordinal", tr: "sıra" },
  { en: "outline", tr: "özetlemek" },
  { en: "particularly", tr: "özellikle" },
  { en: "pension", tr: "emekli maaşı" },
  { en: "permanent", tr: "kalıcı" },
  { en: "permit", tr: "izin vermek" },
  { en: "possess", tr: "sahip olmak" },
  { en: "praise", tr: "övmek" },
  { en: "precede", tr: "-den önce gelmek" },
  { en: "precise", tr: "kesin" },
  { en: "predator", tr: "yırtıcı hayvan" },
  { en: "1predict", tr: "tahmin etmek" },
  { en: "premises", tr: "dayanak noktaları, temel, öz" },
  { en: "prescribe", tr: "reçete yazmak" },
  { en: "preserve", tr: "korumak" },
  { en: "presumably", tr: "muhtemelen" },
  { en: "prevent", tr: "önlemek" },
  { en: "primary", tr: "birincil" },
  { en: "primitive", tr: "ilkel" },
  { en: "probe", tr: "araştırmak" },
  { en: "prompt", tr: "çabuk" },
  { en: "prospect", tr: "olasılık" },
  { en: "rapid", tr: "hızlı" },
  { en: "recall", tr: "hatirlamak" },
  { en: "reckon", tr: "saymak, hesaplamak" },
  { en: "recognition", tr: "tanıma" },
  { en: "recruit", tr: "işe almak" },
  { en: "redundancy", tr: "gereksiz çokluk" },
  { en: "relevant", tr: "i̇lgili" },
  { en: "remark", tr: "söylemek, demek" },
  { en: "remote", tr: "uzak" },
  { en: "replacement", tr: "yer değiştirmek" },
  { en: "resemble", tr: "benzemek" },
  { en: "residue", tr: "artık" },
  { en: "respective", tr: "sırayla" },
  { en: "restrict", tr: "kısıtlamak" },
  { en: "retain", tr: "alıkoymak" },
  { en: "reveal", tr: "ortaya çıkarmak" },
  { en: "reverse", tr: "tersine çevirmek" },
  { en: "revise", tr: "gözden geçirmek" },
  { en: "revival", tr: "canlanma" },
  { en: "rival", tr: "rakip" },
  { en: "savage", tr: "vahşi" },
  { en: "scatter", tr: "saçmak, serpmek" },
  { en: "sediment", tr: "tortu ,cökelti" },
  { en: "sequence", tr: "dizi" },
  { en: "severe", tr: "şiddetli" },
  { en: "sheer", tr: "katıksız, sırf, halis, dimdik, sapmak" },
  { en: "slope", tr: "eğim" },
  { en: "solvent", tr: "çözücü" },
  { en: "specimen", tr: "numune, örnek" },
  { en: "statutory", tr: "kanuni" },
  { en: "steer", tr: "yönlendirmek" },
  { en: "stem", tr: "kök" },
  { en: "stimulate", tr: "uyarmak" },
  { en: "strain", tr: "gerginlik" },
  { en: "subsequent", tr: "sonraki" },
  { en: "subsidiary", tr: "bağlı ortaklık" },
  { en: "substantial", tr: "çok önemli, önemli ölçüde" },
  { en: "subtle", tr: "belirsiz" },
  { en: "suffix", tr: "son ek" },
  { en: "sustain", tr: "sürdürmek" },
  { en: "tender", tr: "hassas, yumuşak" },
  { en: "undergo", tr: "maruz kalmak" },
  { en: "underlie", tr: "temelini oluşturmak" },
  { en: "undertake", tr: "üstlenmek" },
  { en: "vast", tr: "büyük, engin, muazzam" },
  { en: "vegetation", tr: "bitki örtüsü" },
  { en: "velocity", tr: "hız" },
  { en: "venture", tr: "girişim" },
  { en: "verse", tr: "ayet" },
  { en: "withdraw", tr: "geri çekmek" },
  { en: "yield", tr: "verim" },
];
